#!/bin/bash

if [[ "$(id -u)" > "0" ]]; then
    echo "Este script se debe ejecutar como root."
    exit 1
fi

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
RESET=$(tput sgr0)

USERNAME="celasa"
PASSWORD="celasa"

marks="/home/celasa/.config/google-chrome/Default/"

echo "${CYE}Actualizando el sistema...${RESET}"

apt update &> /dev/null

sleep 1

apt upgrade -y > /dev/null

clear

echo "${CGR}Sistema actualizado${RESET}"

sleep 3

echo "${CRE}Espere...${RESET}"

wget -P /tmp/ https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &> /dev/null

wget -P /tmp/  https://raw.githubusercontent.com/marvin09005/ub_cel/refs/heads/main/Bookmarks &> /dev/null

wget -O marcadores https://raw.githubusercontent.com/marvin09005/ub_cel/refs/heads/main/marcadores &> /dev/null

while true; do
    read -rp "¿Desea instalar Spark? ${CYE}S/n: ${RESET}" sn

    if [ -z "$sn" ]; then
        sn="s"
    fi

    case $sn in
        [Ss]* ) 
          echo "Instalando programas..." 
          wget -P /tmp/ https://github.com/igniterealtime/Spark/releases/download/v2.9.3/spark_2_9_3.deb &> /dev/null
          apt install default-jdk default-jre putty samba -y &> /dev/null 
          dpkg -i /tmp/*.deb &> /dev/null
            break 
            ;;
        [Nn]* ) 
          echo "Instalando programas..." 
          apt install default-jdk default-jre putty samba -y &> /dev/null 
          dpkg -i /tmp/*.deb &> /dev/null
            ;;
        * ) 
            printf " Error: solo escribe 's' o 'n'\n\n" 
            ;;
    esac
done

sleep 2

clear


sudo useradd -m -p "$(openssl passwd -1 $PASSWORD)" $USERNAME

if id "$USERNAME" &>/dev/null; then
    echo "${CGR}El usuario '$USERNAME' fue creado exitosamente.${RESET}"
else
    echo "${CRE}Error: No se pudo crear el usuario '$USERNAME'.${RESET}"
fi

cp marcadores /home/$USERNAME
chmod 777 /home/$USERNAME/marcadores

#sleep 3

#echo "${CYE}Copiando configuraciones...${RESET}

#sudo cp -r /home/oe/. /home/$USERNAME/ &> /dev/null

#echo "${CGR}Hecho.${RESET}

#if [ ! -d "$marks" ]; then
#    mkdir -p "$marks" 
#    cp /tmp/Bookmarks "$marks"
#    chown -R $USERNAME:$USERNAME "$marks"
#    echo "Marcadores agregados."
#else
#    echo "${CRE}Error${RESET}"
#fi

#sleep 2

#clear

#echo "${CGR}${BLD}Configuración finalizada."
